# Generated by Django 4.1.5 on 2023-01-07 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0016_rename_client_onboarddata_clientonboard_client_onboard_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('sets', models.IntegerField()),
                ('rep_range', models.CharField(default=None, max_length=100)),
                ('exercise_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_def', models.CharField(choices=[('FB', 'Full Body'), ('UL', 'Upper Lower'), ('PPL', 'Push, Pull, Legs'), ('BS', 'Bro Split'), ('CUS', 'Custom')], max_length=3)),
                ('split_name', models.CharField(max_length=100)),
                ('split_desc', models.TextField()),
                ('split_days', models.CharField(max_length=100)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='main.client')),
                ('coach', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Coach', to='main.coach')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscles', models.CharField(choices=[('CH', 'Chest'), ('BA', 'Back'), ('LE', 'Legs'), ('SH', 'Shoulders'), ('AR', 'Arms'), ('AB', 'Abs')], max_length=2)),
                ('total_sets', models.IntegerField()),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panalyzer.trainingsplit')),
            ],
        ),
        migrations.CreateModel(
            name='LogPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_day', models.CharField(default=None, max_length=50)),
                ('workout_num', models.IntegerField()),
                ('set_num', models.IntegerField()),
                ('weight_unit', models.CharField(choices=[('KG', 'kg'), ('LBS', 'lbs')], max_length=3)),
                ('weight', models.IntegerField()),
                ('reps', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panalyzer.exerciseselection')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseselection',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panalyzer.muscleparts'),
        ),
    ]
