# Generated by Django 4.1.5 on 2023-01-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_client_channel_id'),
        ('panalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resting_heart_rate', models.IntegerField()),
                ('maximum_heart_rate', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
