# Generated by Django 4.1.5 on 2023-01-30 06:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_negotiate_client_and_more'),
        ('panalyzer', '0002_heartperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checkin_pics/')),
            ],
        ),
        migrations.AlterField(
            model_name='exerciseselection',
            name='exercise_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exerciseselection',
            name='rep_range',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseselection',
            name='sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='muscleparts',
            name='total_sets',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='WeeklyCheckins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_weight', models.IntegerField()),
                ('current_weight', models.IntegerField()),
                ('energy_levels', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('strength_levels', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('waist', models.FloatField()),
                ('hips', models.FloatField()),
                ('right_arm', models.FloatField()),
                ('right_quad', models.FloatField()),
                ('right_calf', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coach')),
                ('pictures', models.ManyToManyField(blank=True, to='panalyzer.picture')),
            ],
        ),
    ]
