# Generated by Django 4.1.5 on 2023-01-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_achievement_certificate_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('package_desc', models.CharField(max_length=254)),
                ('duration_type', models.CharField(choices=[('Y', 'Years'), ('M', 'Months'), ('D', 'Days')], max_length=1)),
                ('duration', models.IntegerField()),
                ('base_price', models.IntegerField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coach')),
            ],
        ),
    ]
