# Generated by Django 4.1.5 on 2023-01-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_mapping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
