# Generated by Django 4.1.5 on 2023-01-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_clientonboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientonboard',
            old_name='data',
            new_name='client_onboarddata',
        ),
    ]
