# Generated by Django 4.1.5 on 2023-01-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_client_onboarddata_clientonboard_client_onboard_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='channel_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
