# Generated by Django 4.1.5 on 2023-01-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_client_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='category',
            field=models.CharField(choices=[('F', 'Fitness'), ('L', 'Life Coaching'), ('B', 'Business Coaching'), ('E', 'Executive Coaching'), ('H', 'Health and Wellness Coaching'), ('S', 'Spiritual Coaching'), ('A', 'Athletic Coaching'), ('C', 'Career Coaching')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_subtype',
            field=models.CharField(choices=[('BB', 'Body Building'), ('SF', 'Strength and Fitness'), ('PL', 'Powerlifting')], default='BB', max_length=2),
        ),
    ]
