# Generated by Django 4.1.5 on 2023-01-15 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_blog_share_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='recipients',
            field=models.ManyToManyField(related_name='shares_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
