# Generated by Django 4.1.5 on 2023-01-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_share_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='actual_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Negotiate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiate_message_coach', models.CharField(max_length=255)),
                ('negotiate_message_client', models.CharField(max_length=255)),
                ('negotiate_price_coach', models.IntegerField()),
                ('negotiate_price_client', models.IntegerField()),
                ('updated_price', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('C', 'Cancelled')], default='Pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.package')),
            ],
        ),
    ]
