# Generated by Django 4.1.5 on 2023-01-16 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_mapping_actual_price_negotiate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='negotiate',
            name='negotiate_price_client',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='negotiate',
            name='negotiate_price_coach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='negotiate',
            name='updated_price',
            field=models.IntegerField(default=0),
        ),
    ]
