# Generated by Django 4.1.5 on 2023-02-03 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serving_size', models.FloatField(default=0)),
                ('serving_type', models.CharField(choices=[('O', 'Ounce'), ('GM', 'Gram'), ('P', 'Pound'), ('KG', 'Kilogram'), ('PC', 'Pinch'), ('L', 'Liter'), ('FO', 'Fluid ounce'), ('G', 'Gallon'), ('PT', 'Pint'), ('Q', 'Quart'), ('ML', 'Milliliter'), ('DR', 'Drop'), ('CP', 'Cup'), ('TB', 'Tablespoon'), ('TS', 'Teaspoon')], max_length=2)),
                ('sugar_ad', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('carbs_net', models.FloatField(default=0)),
                ('carbs_diff', models.FloatField(default=0)),
                ('cholestrol', models.FloatField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('fa_monounsaturated', models.FloatField(default=0)),
                ('fa_polyunsaturated', models.FloatField(default=0)),
                ('fa_totalsaturated', models.FloatField(default=0)),
                ('fa_totaltrans', models.FloatField(default=0)),
                ('fibre', models.FloatField(default=0)),
                ('dfe_folate', models.FloatField(default=0)),
                ('folate_food', models.FloatField(default=0)),
                ('folic_acid', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
                ('magnesium', models.FloatField(default=0)),
                ('niacin', models.FloatField(default=0)),
                ('phosphorus', models.FloatField(default=0)),
                ('potassium', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('riboflavin', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('sugar_alcohal', models.FloatField(default=0)),
                ('sugar_total', models.FloatField(default=0)),
                ('thiamin', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('vitamin_a', models.FloatField(default=0)),
                ('vitamin_b12', models.FloatField(default=0)),
                ('vitamin_b6', models.FloatField(default=0)),
                ('vitamin_c', models.FloatField(default=0)),
                ('vitamin_d', models.FloatField(default=0)),
                ('vitamin_e', models.FloatField(default=0)),
                ('vitamin_k', models.FloatField(default=0)),
                ('water', models.FloatField(default=0)),
                ('zinc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
