# Generated by Django 4.1.5 on 2023-02-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_fooditem_serving_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodintake',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
